"""add value_tier to etl_audit_log

Revision ID: 2b91fa9acdf1
Revises: d8373074e495
Create Date: 2026-05-01 03:02:29.994199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b91fa9acdf1'
down_revision: Union[str, None] = 'd8373074e495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etl_audit_log', sa.Column('value_tier', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etl_audit_log', 'value_tier')
    # ### end Alembic commands ###
