#!/usr/bin/env python3
"""
scripts/daily_log.py — Daily Progress Logger + Git Automation
==============================================================
Records daily learning progress and pushes to git.

Usage:
  python scripts/daily_log.py --day 1 --sprint 1 \
      --message "Environment setup complete" \
      --status done

Sprint 01: Basic logging + git push
Sprint 08: Extended with JIRA API integration
"""

import argparse
import subprocess
import sys
import os
from datetime import datetime
from pathlib import Path

# ──────────────────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).resolve().parent.parent
LOG_FILE     = PROJECT_ROOT / "logs" / "progress.md"
SPRINT_LOG   = PROJECT_ROOT / "logs" / "sprint_summary.md"

STATUS_MAP = {
    "done":        "✅ Done",
    "inprogress":  "🔄 In Progress",
    "blocked":     "⚠️  Blocked",
    "failed":      "❌ Failed",
    "skip":        "⏭️  Skipped",
}

# ──────────────────────────────────────────────────────────
def ensure_log_header(log_path: Path) -> None:
    """Create log file with markdown table header if missing."""
    log_path.parent.mkdir(parents=True, exist_ok=True)
    if not log_path.exists() or log_path.stat().st_size == 0:
        with open(log_path, "w", encoding='utf-8') as f:
            f.write("# 📓 90-Day Python DE Journey — Progress Log\n\n")
            f.write("> Auto-generated by `scripts/daily_log.py`\n\n")
            f.write("| Day | Sprint | Date       | Time  | Status        | Notes |\n")
            f.write("|-----|--------|------------|-------|---------------|-------|\n")


def append_log_entry(day: int, sprint: int, message: str, status: str) -> None:
    """Append a row to progress.md."""
    ensure_log_header(LOG_FILE)
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H:%M")
    with open(LOG_FILE, "a", encoding='utf-8') as f:
        f.write(
            f"| {day:03d} | S{sprint:02d}   | {date_str} | {time_str} "
            f"| {status:<13} | {message} |\n"
        )
    print(f"  ✅ Log entry written → {LOG_FILE.relative_to(PROJECT_ROOT)}")


def update_readme_progress(sprint: int) -> None:
    """Update the Sprint progress table in README.md."""
    readme = PROJECT_ROOT / "README.md"
    if not readme.exists():
        return
    content = readme.read_text()
    # Mark current sprint as In Progress if not already Done
    marker = f"| {sprint:02d}     |"
    updated = content.replace(
        f"{marker} ⏳ Pending    |",
        f"{marker} 🔄 In Progress |",
    )
    readme.write_text(updated)


def run_git(cmd: list[str], cwd: Path = PROJECT_ROOT) -> tuple[int, str]:
    """Run a git command and return (returncode, output)."""
    result = subprocess.run(
        ["git", "-C", str(cwd)] + cmd,
        capture_output=True,
        text=True,
    )
    output = (result.stdout + result.stderr).strip()
    return result.returncode, output


def git_commit_push(day: int, sprint: int, message: str) -> bool:
    """Stage, commit, and push current branch."""
    commit_msg = f"[DAY-{day:03d}][S{sprint:02d}] {message}"

    # Stage everything
    rc, out = run_git(["add", "."])
    if rc != 0:
        print(f"  ⚠️  git add warning: {out}")

    # Check if there's anything to commit
    rc, status = run_git(["status", "--porcelain"])
    if not status:
        print("  ℹ️  Nothing new to commit — already up to date")
        return True

    # Commit
    rc, out = run_git(["commit", "-m", commit_msg])
    if rc != 0:
        print(f"  ❌ git commit failed: {out}")
        return False
    print(f"  ✅ Committed: {commit_msg}")

    # Push
    rc, out = run_git(["push"])
    if rc == 0:
        print("  ✅ Pushed to remote")
        return True
    elif "set-upstream" in out or "no upstream" in out.lower():
        # Try setting upstream
        rc2, branch_out = run_git(["branch", "--show-current"])
        branch = branch_out.strip()
        rc3, push_out = run_git(["push", "--set-upstream", "origin", branch])
        if rc3 == 0:
            print(f"  ✅ Pushed (upstream set → origin/{branch})")
            return True
        print(f"  ⚠️  Push failed: {push_out}")
        return False
    else:
        print(f"  ⚠️  Push warning: {out}")
        return False


def create_day_folder(day: int, sprint: int) -> Path:
    """Ensure sprint/day folder exists with a placeholder log."""
    day_dir = PROJECT_ROOT / f"sprint-{sprint:02d}" / f"day-{day:02d}"
    day_dir.mkdir(parents=True, exist_ok=True)
    placeholder = day_dir / f"day_{day:03d}_notes.md"
    if not placeholder.exists():
        with open(placeholder, "w", encoding='utf-8') as f:
            f.write(f"# Day {day:03d} Notes — Sprint {sprint:02d}\n\n")
            f.write(f"Date: {datetime.now().strftime('%Y-%m-%d')}\n\n")
            f.write("## Today's Tasks\n\n- [ ] \n\n")
            f.write("## Learnings\n\n\n## Issues / Blockers\n\n\n")
            f.write("## Tomorrow's Plan\n\n")
    return day_dir


def print_git_summary() -> None:
    """Print a brief git status summary."""
    rc, branch = run_git(["branch", "--show-current"])
    rc2, log = run_git(["log", "--oneline", "-3"])
    print(f"\n  📋 Git Status:")
    print(f"     Branch: {branch}")
    print("     Recent commits:")
    for line in log.splitlines():
        print(f"       {line}")


# ──────────────────────────────────────────────────────────
def main() -> None:
    parser = argparse.ArgumentParser(
        description="Log daily DE journey progress and push to git",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    parser.add_argument(
        "--day", type=int, required=True,
        help="Day number (1-90)",
    )
    parser.add_argument(
        "--sprint", type=int, default=None,
        help="Sprint number (1-13). Auto-calculated if omitted.",
    )
    parser.add_argument(
        "--message", "-m", type=str, required=True,
        help="Progress description (what you did today)",
    )
    parser.add_argument(
        "--status", "-s", type=str, default="done",
        choices=list(STATUS_MAP.keys()),
        help="Completion status (default: done)",
    )
    parser.add_argument(
        "--no-push", action="store_true",
        help="Log only, do not push to git",
    )
    args = parser.parse_args()

    # Auto-calculate sprint if not provided
    sprint = args.sprint or ((args.day - 1) // 7 + 1)

    status_label = STATUS_MAP[args.status]

    print(f"\n{'─' * 50}")
    print(f"  📅 Day {args.day:03d} | Sprint {sprint:02d}")
    print(f"  📝 {args.message}")
    print(f"  📌 {status_label}")
    print(f"{'─' * 50}\n")

    # 1. Create day folder
    day_dir = create_day_folder(args.day, sprint)
    print(f"  ✅ Day folder ready → {day_dir.relative_to(PROJECT_ROOT)}")

    # 2. Append to progress log
    append_log_entry(args.day, sprint, args.message, status_label)

    # 3. Update README sprint table
    update_readme_progress(sprint)

    # 4. Git commit + push
    if not args.no_push:
        success = git_commit_push(args.day, sprint, args.message)
        print_git_summary()
        if not success:
            print("\n  ⚠️  Git push failed — check remote config")
            sys.exit(1)
    else:
        print("  ℹ️  --no-push flag set: skipping git push")

    print(f"\n  🎯 Day {args.day:03d} logged successfully.\n")


if __name__ == "__main__":
    main()
